services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: blood_donation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3251
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:3251@db/blood_donation_db
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend